import json
from typing import List, Optional

from openai import AsyncOpenAI
from pydantic import BaseModel, Field, model_validator

from config import settings


SYSTEM_PROMPT = """You are an expert scientific data extractor. Your job is to take a messy, natural-language scientific question or hypothesis and extract the core variables into a strictly typed JSON object.

Pay careful attention to the required and optional fields. If a quantity or environmental constraint is mentioned, ensure it is captured. If the user is just asking if something has been done before, set `is_novelty_search` to true.

Always preserve the exact raw text provided by the user in the `original_input` field.

Quality Validation Rules:
1. Outcome Metric: It must contain quantitative thresholds (e.g., numbers, percentages). If it doesn't, add a clarifying question asking for them.
2. Control Condition: It must be specified or clearly implied. If it's missing, add a clarifying question.
3. Intervention: It must be specific. If generic terms like "AI", "model", "drug", or "chemical" are used, add a clarifying question.

If any of these rules fail, populate the `clarifying_questions` list with specific, targeted questions directed at the user to gather the missing details.

# Example 1
User Input: "We want to see if swapping sucrose for trehalose in HeLa cell freezing protocols on ice improves cell viability by 20% compared to baseline."

Output JSON:
{
  "original_input": "We want to see if swapping sucrose for trehalose in HeLa cell freezing protocols on ice improves cell viability by 20% compared to baseline.",
  "domain": "Cell Biology",
  "subject": "HeLa cells",
  "intervention": "trehalose (instead of sucrose)",
  "outcome_metric": "cell viability (20% improvement)",
  "is_novelty_search": false,
  "control_condition": "sucrose (baseline)",
  "target_quantity": null,
  "environmental_constraints": ["ice bath"],
  "clarifying_questions": []
}

# Example 2
User Input: "Has anyone tried administering a chemical to mice to measure improvements in happiness?"

Output JSON:
{
  "original_input": "Has anyone tried administering a chemical to mice to measure improvements in happiness?",
  "domain": "Biology / Pharmacology",
  "subject": "mice",
  "intervention": "chemical",
  "outcome_metric": "improvements in happiness",
  "is_novelty_search": true,
  "control_condition": null,
  "target_quantity": null,
  "environmental_constraints": [],
  "clarifying_questions": [
    "What specific chemical are you proposing to administer?",
    "How exactly will 'happiness' be quantified? (e.g., specific behavioral metrics or percentages)",
    "What is the control condition for comparison?"
  ]
}
"""

DOMAIN_KEY_PROMPT = """Extract a concise snake_case domain key from the scientific hypothesis below.
The key must: be 2-5 words joined by underscores, describe the biological/chemical system being studied,
be suitable as a filesystem slug (lowercase, no spaces, no special chars).
Examples: gut_permeability_mouse, crispr_t_cell_therapy, alzheimers_tau_phosphorylation, antibiotic_resistance_ecoli
Return ONLY the snake_case key, nothing else."""


class ParsedHypothesis(BaseModel):
    original_input: str = Field(
        description="The full natural-language hypothesis text originally provided by the user."
    )
    domain: str = Field(
        description="The scientific domain or field of study, e.g., Cell Biology, Chemistry, Diagnostics."
    )
    subject: str = Field(
        description="The core subject of the experiment, e.g., C57BL/6 mice, HeLa cells, or a specific compound."
    )
    intervention: str = Field(
        description="The chemical, drug, process, or action being applied to the subject."
    )
    outcome_metric: str = Field(
        description="What is being measured as the outcome? e.g., intestinal permeability, cell viability, reaction yield."
    )
    is_novelty_search: bool = Field(
        description="Set to true if the user is just asking if this experiment or intervention has been done before, rather than proposing to do it."
    )
    control_condition: Optional[str] = Field(
        default=None,
        description="What the intervention is being compared to (the control group or baseline condition)."
    )
    target_quantity: Optional[str] = Field(
        default=None,
        description="The scale, concentration, or amount requested. E.g., '10kg', '5 moles', '10 mg/mL'. Leave null if not specified."
    )
    environmental_constraints: List[str] = Field(
        default_factory=list,
        description="Required lab conditions. E.g., 'O2 exclusion', 'light exclusion', 'ice bath', 'moisture exclusion'."
    )
    clarifying_questions: List[str] = Field(
        default_factory=list,
        description="Specific questions generated by the LLM when information is missing (e.g., 'What concentration of compound X should be used?' or 'What is the control condition?')."
    )
    domain_key: str = Field(
        description="Snake_case domain key for EdgeQuake workspace routing, e.g. gut_permeability_mouse"
    )

    @model_validator(mode='after')
    def validate_quality(self) -> 'ParsedHypothesis':
        # If there are clarifying questions, the LLM has already determined the input is incomplete.
        if self.clarifying_questions:
            return self

        # 1. Validate outcome_metric contains quantitative thresholds (numbers, percentages, or specific math symbols)
        if self.outcome_metric and not any(char.isdigit() or char in '%/<>' for char in self.outcome_metric):
            raise ValueError("outcome_metric must contain quantitative thresholds (e.g., numbers, percentages).")

        # 2. Validate control_condition is specified or clearly implied
        if not self.control_condition or self.control_condition.strip().lower() in ['none', 'n/a', 'null']:
            raise ValueError("control_condition must be specified or clearly implied.")

        # 3. Validate intervention is specific
        generic_terms = ["ai", "model", "algorithm", "drug", "chemical", "test", "compound", "software"]
        if self.intervention and self.intervention.strip().lower() in generic_terms:
            raise ValueError(f"intervention '{self.intervention}' is too generic. Please be specific.")

        return self


async def parse_hypothesis(hypothesis: str) -> ParsedHypothesis:
    """Parse a natural-language scientific hypothesis into a structured ParsedHypothesis.

    Makes two Groq calls:
    1. Structured hypothesis extraction (all fields except domain_key)
    2. Domain key extraction (snake_case workspace routing key)

    Args:
        hypothesis: Scientific hypothesis text (50-2000 characters)

    Returns:
        ParsedHypothesis with all fields populated including domain_key

    Raises:
        ValueError: If hypothesis length is outside 50-2000 chars
    """
    if len(hypothesis) < 50 or len(hypothesis) > 2000:
        raise ValueError("Hypothesis must be 50-2000 characters")

    client = AsyncOpenAI(
        base_url="https://api.groq.com/openai/v1",
        api_key=settings.groq_api_key,
    )

    # First call: parse structured hypothesis into all fields except domain_key
    first_response = await client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": hypothesis},
        ],
    )
    hypothesis_data = json.loads(first_response.choices[0].message.content)

    # Second call: extract domain key
    second_response = await client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": DOMAIN_KEY_PROMPT},
            {"role": "user", "content": hypothesis},
        ],
    )
    domain_key = second_response.choices[0].message.content.strip()

    return ParsedHypothesis(**hypothesis_data, domain_key=domain_key)
