from typing import List, Optional
from pydantic import BaseModel, Field, model_validator
import re


class ParsedHypothesis(BaseModel):
    original_input: str = Field(
        description="The full natural-language hypothesis text originally provided by the user."
    )
    domain: str = Field(
        description="The scientific domain or field of study, e.g., Cell Biology, Chemistry, Diagnostics."
    )
    subject: str = Field(
        description="The core subject of the experiment, e.g., C57BL/6 mice, HeLa cells, or a specific compound."
    )
    intervention: str = Field(
        description="The chemical, drug, process, or action being applied to the subject."
    )
    outcome_metric: str = Field(
        description="What is being measured as the outcome? e.g., intestinal permeability, cell viability, reaction yield."
    )
    is_novelty_search: bool = Field(
        description="Set to true if the user is just asking if this experiment or intervention has been done before, rather than proposing to do it."
    )
    control_condition: Optional[str] = Field(
        default=None,
        description="What the intervention is being compared to (the control group or baseline condition)."
    )
    target_quantity: Optional[str] = Field(
        default=None,
        description="The scale, concentration, or amount requested. E.g., '10kg', '5 moles', '10 mg/mL'. Leave null if not specified."
    )
    environmental_constraints: List[str] = Field(
        default_factory=list,
        description="Required lab conditions. E.g., 'O2 exclusion', 'light exclusion', 'ice bath', 'moisture exclusion'."
    )
    clarifying_questions: List[str] = Field(
        default_factory=list,
        description="Specific questions generated by the LLM when information is missing (e.g., 'What concentration of compound X should be used?' or 'What is the control condition?')."
    )

    @staticmethod
    def _has_quantitative_signal(text: Optional[str]) -> bool:
        if not text:
            return False
        return any(char.isdigit() or char in "%/<>" for char in text)

    @staticmethod
    def _is_generic_term(text: Optional[str]) -> bool:
        if not text:
            return True
        lowered = text.strip().lower()
        generic_patterns = [
            r"\bai\b",
            r"\bmodel\b",
            r"\balgorithm\b",
            r"\bdrug(s)?\b",
            r"\bchemical(s)?\b",
            r"\bcompound(s)?\b",
            r"\btreatment(s)?\b",
            r"\btherapy\b",
            r"\bcell(s)?\b",
            r"\bmouse\b|\bmice\b|\banimal(s)?\b",
            r"\btest\b",
            r"\bsoftware\b",
        ]
        return any(re.search(pattern, lowered) for pattern in generic_patterns)

    @model_validator(mode='after')
    def validate_quality(self) -> 'ParsedHypothesis':
        # Do not fail hard for incomplete inputs. Always return with actionable clarifying questions.
        questions = list(self.clarifying_questions)

        if not self._has_quantitative_signal(self.outcome_metric):
            questions.append(
                "How will the outcome be quantified (numeric threshold, percentage, or cutoff)?"
            )

        if (
            not self.control_condition
            or self.control_condition.strip().lower() in ['none', 'n/a', 'null']
            or self._is_generic_term(self.control_condition)
        ):
            questions.append(
                "What exact control condition or baseline comparator should be used?"
            )

        if self._is_generic_term(self.intervention):
            questions.append(
                "What is the exact intervention (specific compound, strain, protocol, or model) instead of a generic term?"
            )

        if self._is_generic_term(self.subject):
            questions.append(
                "What is the exact subject/system (cell line, organism strain, cohort, or material identity)?"
            )

        # De-duplicate while preserving order.
        self.clarifying_questions = list(dict.fromkeys(q.strip() for q in questions if q.strip()))
        return self

