from typing import List, Optional
from pydantic import BaseModel, Field, model_validator
import re

class ParsedHypothesis(BaseModel):
    original_input: str = Field(
        description="The full natural-language hypothesis text originally provided by the user."
    )
    domain: str = Field(
        description="The scientific domain or field of study, e.g., Cell Biology, Chemistry, Diagnostics."
    )
    subject: str = Field(
        description="The core subject of the experiment, e.g., C57BL/6 mice, HeLa cells, or a specific compound."
    )
    intervention: str = Field(
        description="The chemical, drug, process, or action being applied to the subject."
    )
    outcome_metric: str = Field(
        description="What is being measured as the outcome? e.g., intestinal permeability, cell viability, reaction yield."
    )
    is_novelty_search: bool = Field(
        description="Set to true if the user is just asking if this experiment or intervention has been done before, rather than proposing to do it."
    )
    control_condition: Optional[str] = Field(
        default=None,
        description="What the intervention is being compared to (the control group or baseline condition)."
    )
    target_quantity: Optional[str] = Field(
        default=None,
        description="The scale, concentration, or amount requested. E.g., '10kg', '5 moles', '10 mg/mL'. Leave null if not specified."
    )
    environmental_constraints: List[str] = Field(
        default_factory=list,
        description="Required lab conditions. E.g., 'O2 exclusion', 'light exclusion', 'ice bath', 'moisture exclusion'."
    )
    clarifying_questions: List[str] = Field(
        default_factory=list,
        description="Specific questions generated by the LLM when information is missing (e.g., 'What concentration of compound X should be used?' or 'What is the control condition?')."
    )

    @model_validator(mode='after')
    def validate_quality(self) -> 'ParsedHypothesis':
        # If there are clarifying questions, the LLM has already determined the input is incomplete.
        if self.clarifying_questions:
            return self
            
        # 1. Validate outcome_metric contains quantitative thresholds (numbers, percentages, or specific math symbols)
        if self.outcome_metric and not any(char.isdigit() or char in '%/<>' for char in self.outcome_metric):
            raise ValueError("outcome_metric must contain quantitative thresholds (e.g., numbers, percentages).")
            
        # 2. Validate control_condition is specified or clearly implied
        if not self.control_condition or self.control_condition.strip().lower() in ['none', 'n/a', 'null']:
            raise ValueError("control_condition must be specified or clearly implied.")
            
        # 3. Validate intervention is specific
        generic_terms = ["ai", "model", "algorithm", "drug", "chemical", "test", "compound", "software"]
        if self.intervention and self.intervention.strip().lower() in generic_terms:
            raise ValueError(f"intervention '{self.intervention}' is too generic. Please be specific.")
            
        return self
